Update facebook and instagram ip ranges

diff --git a/facebook and instagram ip ranges b/facebook and instagram ip ranges
--- a/facebook and instagram ip ranges
+++ b/facebook and instagram ip ranges
@@ -17,3 +17,201 @@
 204.15.20.0/22
 50.237.157.0/24
 162.250.133.0/24
+
+Converted from CIDR notation (also known as "slash notation") into IP Range
+https://gist.github.com/deardooley/f7bdf7e464680abb47faf6f69fc5beea
+
+
+
+31.13.24.0-31.13.31.255
+31.13.64.0-31.13.127.255
+45.64.40.0-45.64.43.255
+66.220.144.0-66.220.159.255
+69.63.176.0-69.63.191.255
+69.171.224.0-69.171.255.255
+74.119.76.0-74.119.79.255
+102.132.96.0-102.132.111.255
+103.4.96.0-103.4.99.255
+129.134.0.0-129.134.255.255
+147.75.208.0-147.75.223.255
+157.240.0.0-157.240.255.255
+173.252.64.0-173.252.127.255
+179.60.192.0-179.60.195.255
+185.60.216.0-185.60.219.255
+185.89.216.0-185.89.219.255
+204.15.20.0-204.15.23.255
+50.237.157.0-
+162.250.133.0-
+
+
+
+
+#!/usr/bin/env bash
+
+# Print usage
+function usage {
+  echo -n "$(basename $0) CIDR...
+$(basename $0) [OPTION] CIDR...
+
+This script prints the ip range or full list of ip addresses for one or more CIDR.
+
+ Options:
+  -a, --all             Print the list of ip addresses rather than the range for each CIDR
+  -h, --help            Display this help and exit
+"
+}
+
+# Exit with error code and statement
+function die() { out "$@"; exit 1; } >&2
+
+############################
+##  Methods
+############################
+prefix_to_bit_netmask() {
+    prefix=$1;
+    shift=$(( 32 - prefix ));
+
+    bitmask=""
+    for (( i=0; i < 32; i++ )); do
+        num=0
+        if [ $i -lt $prefix ]; then
+            num=1
+        fi
+
+        space=
+        if [ $(( i % 8 )) -eq 0 ]; then
+            space=" ";
+        fi
+
+        bitmask="${bitmask}${space}${num}"
+    done
+    echo $bitmask
+}
+
+bit_netmask_to_wildcard_netmask() {
+    bitmask=$1;
+    wildcard_mask=
+    for octet in $bitmask; do
+        wildcard_mask="${wildcard_mask} $(( 255 - 2#$octet ))"
+    done
+    echo $wildcard_mask;
+}
+
+check_net_boundary() {
+    net=$1;
+    wildcard_mask=$2;
+    is_correct=1;
+    for (( i = 1; i <= 4; i++ )); do
+        net_octet=$(echo $net | cut -d '.' -f $i)
+        mask_octet=$(echo $wildcard_mask | cut -d ' ' -f $i)
+        if [ $mask_octet -gt 0 ]; then
+            if [ $(( $net_octet&$mask_octet )) -ne 0 ]; then
+                is_correct=0;
+            fi
+        fi
+    done
+    echo $is_correct;
+}
+
+# native bash script to expand cidr
+function coldcidr {
+
+		net=$(echo $1 | cut -d '/' -f 1);
+		prefix=$(echo $1 | cut -d '/' -f 2);
+		do_processing=1;
+
+		bit_netmask=$(prefix_to_bit_netmask $prefix);
+
+		wildcard_mask=$(bit_netmask_to_wildcard_netmask "$bit_netmask");
+		is_net_boundary=$(check_net_boundary $net "$wildcard_mask");
+
+		if [ $is_net_boundary -ne 1 ] ; then
+        echo "CIDR base address $net didn't start at a subnet boundary" 1>&2
+        echo    ## move to a new line
+        if [[ $REPLY =~ ^[Yy]$ ]]; then
+            do_processing=1;
+        else
+            do_processing=0;
+        fi
+    fi
+
+		if [ $do_processing -eq 1 ]; then
+				str=
+				for (( i = 1; i <= 4; i++ )); do
+						range=$(echo $net | cut -d '.' -f $i)
+						mask_octet=$(echo $wildcard_mask | cut -d ' ' -f $i)
+						if [ $mask_octet -gt 0 ]; then
+								range="{$range..$(( $range | $mask_octet ))}";
+						fi
+						str="${str} $range"
+				done
+				ips=$(echo $str | sed "s, ,\\.,g"); ## replace spaces with periods, a join...
+
+				if (( DISPLAYRANGE )); then
+					echo $(eval echo $ips | tr ' ' '\n' | (head -n1 && echo '-' && tail -n1))
+				else
+					eval echo $ips | tr ' ' '\n'
+				fi
+		else
+				exit 1
+		fi
+
+}
+
+# Wrapper to print prips output as a range
+function hotcidr {
+
+		if (( DISPLAYRANGE )); then
+			echo $(prips $1 | (head -n1 && echo '-' && tail -n1))
+		else
+			prips $1
+		fi
+
+}
+
+
+############################
+## Main
+############################
+
+function main {
+
+	# Use the prips util if present on the local system
+	EXPANDCMD=hotcidr
+	if [[ -z $(which prips) ]]; then
+		# if prips is not available, we fall back on a slower native bash function
+		# implemented above.
+		EXPANDCMD=coldcidr
+	fi
+
+	cidrs=$@
+
+	# iterate over all cidr given in the input and print
+	for cidr in ${cidrs[@]}; do
+
+		$EXPANDCMD "$cidr"
+
+	done
+}
+
+
+# we default to printing a range, but if a list of ip addresses
+# is desired, we will print that
+DISPLAYRANGE=1
+
+# parse arguments
+while [[ $1 = -?* ]]; do
+  case $1 in
+    -h|--help) usage >&2; exit 0;;
+    -a|--all) DISPLAYRANGE=0;;
+  	*) die "invalid option: $1" ;;
+  esac
+  shift
+done
+
+if [[ -z "$@" ]]; then
+  usage
+fi
+
+# process the cidrs passed in as arguments
+main "$@"
